baseURL: /
languageCode: en-us
publishDir: public/
canonifyURLs: true
title: guac
theme: hugo-fresh
googleAnalytics: G-VVPLWNX4L9
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/guac-logo-squareish.png
    link: /
    text: GUAC
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Know your software supply chain
    # Hero subtitle (optional)
    subtitle: Use GUAC to get organized and actionable insights into your software supply chain security position. 
    # Button text
    button1text: Find out more
    button1link: "#problem"
    button2text: Soon in Beta!
    button2link: "https://docs.guac.sh"

    # Hero image (from static/images/___)
    #image: illustrations/worker.svg
    image: logos/guac-logo.png


    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Community
    url: /community
  - title: Blogs
    url: /blogs
  - title: Demos
    url: https://docs.guac.sh/guac-use-cases/
  - title: Docs
    url: https://docs.guac.sh/
  - title: Github
    url: https://github.com/guacsec/guac
    button: true


  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Log in
  #   url: /
  # - title: Sign up
  #   url: /
  #   button: true
  #sidebar:
  #  # Logo (from /images/logos/___.svg)
  #  logo: fresh-square
  #  sections:
  #  - title: User
  #    icon: user
  #    links:
  #    - text: Profile
  #      url: /
  #    - text: Account
  #      url: /
  #    - text: Settings
  #      url: /
  #  - title: Messages
  #    icon: envelope
  #    links:
  #    - text: Inbox
  #      url: /
  #    - text: Compose
  #      url: /
  #  - title: Images
  #    icon: image
  #    links:
  #    - text: Library
  #      url: /
  #    - text: Upload
  #      url: /
  #  - title: Settings
  #    icon: cog
  #    links:
  #    - text: User settings
  #      url: /
  #    - text: App settings
  #      url: /
  section1:
    title: How GUAC can help you 
    subtitle: These are just a few examples of insights that GUAC can give you to improve your software security posture
    tiles:
    - title: Proactive
      icon: mouse-globe
      texts:
      - text: Find the most used critical components in a software supply chain ecosystem.
      - text: Find weaknesses in overall security posture.
      - text: Prevent supply chain compromises before they happen.
      - text: Find exposures to risky dependencies.
      url: https://github.com/guacsec/guac
      buttonText: Find GUAC
    - title: Operational
      icon: laptop-cloud
      texts: 
      - text: Look for evidence that the application you're about to deploy meets your organization's policies.
      - text: Track if all binaries in production trace back to a securely managed repository.
      url: https://github.com/guacsec/guac
      buttonText: Get GUAC
    - title: Reactive
      icon: doc-sync
      texts: 
      - text: Find which parts of your organization's inventory are affected by a new vulnerability.
      - text: Track a suspicious project lifecycle event back to the risk that was introduced into your organization.
      - text: Learn how an open source project deprecation affects you.
      url: https://github.com/guacsec/guac
      buttonText: Eat GUAC



  section2:
    title: What does GUAC do?
    subtitle: ""
    features:
    - title: Establishes connections between your software catalog
      icon: illustrations/undraw/undraw_share_link_re_54rx.svg
    - title: Unveils gaps in the software supply chain data using other data sources
      icon: illustrations/undraw/undraw_personal_data_re_ihde.svg
    - title: Identifies threats in your supply chain and provides a path to remediation
      icon: illustrations/undraw/undraw_software_engineer_re_tnjc.svg

  sectionCollab:
    title: In Open Source collaboration with
    others:
    - text: and other open source contributors...
      link: https://github.com/guacsec/guac/graphs/contributors
    orgsBig:
    - name: Google
      logo: google.png
      # <!-- logos at images/logos/ -->
      link: https://google.com/
    - name: Kusari
      logo: kusari.svg
      link: https://kusari.dev
    orgs:
    - name: Purdue University
      link: https://www.purdue.edu/
      logo: purdue.png
    - name: Citi
      link: https://www.citi.com/
      logo: citi.png
    - name: and many open source contributors...
      link: https://github.com/guacsec/guac/contributors




  sectionGithub:
    title: What's next?
    subtitle: Learn more about GUAC
    button1Text: Github
    button1Link: https://github.com/guacsec/guac
    button2Text: Demos
    button2Link: https://docs.guac.sh/guac-use-cases/

  sectionProblem:
    title: The current problem with software supply chain security
    subtitle: Software supply chain attacks are on the rise and unless you have enterprise-scale security and IT funding, it’s hard to know what your software is at risk for and how to protect it. Many tools are available to help you generate Software Bills of Materials (SBOMs), signed attestations, and vulnerabilities, but they stop there, leaving you to figure out how one piece of software affects another. 

  sectionVision:
    title: Our Vision
    subtitle: GUAC (Graph for Understanding Artifact Composition) aims to fill in the gaps by ingesting software metadata, like SBOMs, and mapping out relationships between software. When you know how one piece of software affects another, you’ll be able to fully understand your software security position and act as needed. 
    image: illustrations/undraw/undraw_image_viewer_re_7ejc.svg



  sectionBeta:
    title: GUAC Beta is coming soon!
    subtitle: Coming soon!
      #subtitle: In the Beta, you can run GUAC internally in your organization to take active steps to manage risk. Currently, you can query SLSA provenance, SBOMs, and OpenSSF Scorecards. In the future, GUAC aims to run as a public service where high-fidelity supply chain security metadata can be attained for every software ecosystem.
    buttonText: Check out Beta Soon!
    buttonLink: "https://github.com/guacsec/guac/demos"




  sectionUniid:
    title: Try the GUAC Beta today!
    subtitle: Get started with GUAC today by taking a look at our GUAC Beta demos and tutorials!
    buttonText: Check out our demos
    buttonLink: "https://github.com/guacsec/guac/demos"


  section4:
    title: What people are saying about GUAC!
    subtitle: Hear what our community and partners have to say about GUAC!
    clients:
    - name: Dejan Bosanac
      quote: With the growing number of software supply chain security (SSCS) data, tools that allow us to find relevant information are crucial. Guac, providing graph representation of software packages, dependencies, vulnerabilities, attestations, etc. is a great tool for use cases in this domain. With mechanisms to ingest and certify data from various sources and GraphQL API to later query those data, we see it as a good foundation for our current and future SSCS efforts. Being a true open source initiative with a welcoming community is just a plus.  
      job: Engineer at Red Hat
      img: 3
    - name: Hemil Kadakia
      quote: At Yahoo, we have found immense value and significant efficiency by utilizing the open source project GUAC. GUAC has allowed us to streamline our processes and increase efficiency in a way that was not possible before. It allows us to ingest large number of SBOMs and also provides an interface to visualize the current state of images & packages used at Yahoo in real time. We look forward to continuing to utilize GUAC and contribute to its growth in any way we can.
      job: Sr. Mgr. Software Dev Engineering, Paranoids, Yahoo.
      img: 3
    - name: Sean Terretta
      quote: As the CTO of ClearAlpha, I can't recommend GUAC enough for companies looking to boost their software security. GUAC's innovative approach to software supply chain security helps uncover hidden gaps and threats as we’re downloading dependencies and building apps, making it a perfect fit for our “solve it earlier” mindset at ClearAlpha. It also lines up with our commitment to transparency, open-source principles, and continuous learning. GUAC works well in teams practicing the rugged software manifesto, focusing on strong coding practices, constant testing, and automated tools to enhance security. Plus, its ability to trace risks back to their source aligns with our proactive risk awareness goals, enabling companies to spot and tackle potential issues early on. GUAC is just a fantastic tool to help any organization improve their software security with principles we all should value. If you're a tech founder, you'll definitely want to have GUAC on your team!
      job: CTO at ClearAlpha
      img: 3
    - name: Anoop Gopalakrishnan
      quote: GUAC came along as an open-source software at the right time helping us pivot away from building a bespoke solution and involving ourselves with the best minds behind the project. The value we see with GUAC is its flexibility and plugin architecture leading up to helping the users achieve compliance at different levels. The biggest benefit of GUAC has been producing it in the open with a widespread  community behind it, from Google to Kusari and others. As the industry progresses, the threats to the software supply chain will become more complex, and relying on a tool backed by people with many years of experience in the area would make things easier for Guidewire to consume.
      job: Vice President Of Engineering at Guidewire Software
      img: 3

  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
